
/**
 * @typedef {object} TmdbMovieDiscovery
 * @property {number} page
 * @property {object[]} results
 * @property {boolean} results.adult
 * @property {string} results.backdrop_path
 * @property {number[]} results.genre_ids
 * @property {number} results.id
 * @property {string} results.original_language
 * @property {string} results.original_title
 * @property {string} results.overview
 * @property {number} results.popularity
 * @property {string} results.poster_path
 * @property {string} results.release_date
 * @property {string} results.title
 * @property {boolean} results.video
 * @property {number} results.vote_average
 * @property {number} results.vote_count
 * @property {number} total_pages
 * @property {number|undefined} total_results
 */

/**
 * @typedef {object} TmdbMovie
 * @property {boolean} adult
 * @property {string} backdrop_path
 * @property {object} belongs_to_collection
 * @property {number} belongs_to_collection.id
 * @property {string} belongs_to_collection.name
 * @property {string} belongs_to_collection.poster_path
 * @property {string} belongs_to_collection.backdrop_path
 * @property {number} budget
 * @property {object[]} genres
 * @property {number} genres.id
 * @property {string} genres.name
 * @property {string} homepage
 * @property {number} id
 * @property {string} imdb_id
 * @property {string} original_language
 * @property {string} original_title
 * @property {string} overview
 * @property {number} popularity
 * @property {string} poster_path
 * @property {object[]} production_companies
 * @property {number} production_companies.id
 * @property {string|null} production_companies.logo_path
 * @property {string} production_companies.name
 * @property {string} production_companies.origin_country
 * @property {object[]} production_countries
 * @property {string} production_countries.iso_3166_1
 * @property {string} production_countries.name
 * @property {string} release_date
 * @property {number} revenue
 * @property {number} runtime
 * @property {object[]} spoken_languages
 * @property {string} spoken_languages.english_name
 * @property {string} spoken_languages.iso_639_1
 * @property {string} spoken_languages.name
 * @property {string} status
 * @property {string} tagline
 * @property {string} title
 * @property {boolean} video
 * @property {number} vote_average
 * @property {number} vote_count
 * @property {object} credits
 * @property {object[]} credits.cast
 * @property {boolean} credits.cast.adult
 * @property {number} credits.cast.gender
 * @property {number} credits.cast.id
 * @property {string} credits.cast.known_for_department
 * @property {string} credits.cast.name
 * @property {string} credits.cast.original_name
 * @property {number} credits.cast.popularity
 * @property {string|null} credits.cast.profile_path
 * @property {number} credits.cast.cast_id
 * @property {string} credits.cast.character
 * @property {string} credits.cast.credit_id
 * @property {number} credits.cast.order
 * @property {object[]} credits.crew
 * @property {boolean} credits.crew.adult
 * @property {number} credits.crew.gender
 * @property {number} credits.crew.id
 * @property {string} credits.crew.known_for_department
 * @property {string} credits.crew.name
 * @property {string} credits.crew.original_name
 * @property {number} credits.crew.popularity
 * @property {null|string} credits.crew.profile_path
 * @property {string} credits.crew.credit_id
 * @property {string} credits.crew.department
 * @property {string} credits.crew.job
 * @property {object} videos
 * @property {object[]} videos.results
 * @property {string} videos.results.iso_639_1
 * @property {string} videos.results.iso_3166_1
 * @property {string} videos.results.name
 * @property {string} videos.results.key
 * @property {string} videos.results.site
 * @property {number} videos.results.size
 * @property {string} videos.results.type
 * @property {boolean} videos.results.official
 * @property {string} videos.results.published_at
 * @property {string} videos.results.id
 */
